"""RAG trace entity — persisted observability record for every query.

Captures the full request → retrieval → rerank → LLM pipeline as a single
row per query, with timing metrics and per-stage slice snapshots for
later analysis (debugging bad answers, A/B-ing rerankers, measuring
hybrid vs pure-vector performance, etc.).

Note on FK targets (intentional design):

- ``session_id``  →  ``chat_sessions.id`` (autoincrement PK, int)
- ``user_id``     →  ``users.id``        (autoincrement PK, int)

The route layer receives a string UUID (``session_uuid``) from the
client. ``chat_history_service.get_internal_session_id(db, chat_id_uuid)``
translates it to the int FK this table needs.
"""
from sqlalchemy import (
    JSON,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column
from datetime import datetime

from app.entity.base import Base


class RAG_traces(Base):
    __tablename__ = "rag_traces"

    # Primary Key
    id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=True
    )

    # --- Query Details ---
    original_query: Mapped[str] = mapped_column(
        Text, nullable=False, index=True, comment="The original user query"
    )
    transformation_technique: Mapped[str | None] = mapped_column(
        String(100), nullable=True,
        comment="Technique used (e.g., 'hyde', 'rewrite', 'decompose', 'passthrough')",
    )
    transformed_query: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="The query after transformation (joined with ' || ' if multiple)"
    )

    # --- Retrieval & Reranking Details ---
    # JSON stores lists of {content, metadata, score?} dicts at each stage.
    retrieved_chunks: Mapped[list[dict] | None] = mapped_column(
        JSON, nullable=True,
        comment="Initial chunks from hybrid search (BM25 + vector), BEFORE reranking",
    )
    reranked_chunks: Mapped[list[dict] | None] = mapped_column(
        JSON, nullable=True,
        comment="Chunks after the cross-encoder reranker (with score field)",
    )

    # --- LLM Generation Details ---
    context_passed_to_llm: Mapped[list[dict] | None] = mapped_column(
        JSON, nullable=True,
        comment="Dedup'd final context chunks used to build the LLM prompt",
    )
    llm_response: Mapped[str] = mapped_column(
        Text, nullable=False, comment="The final response generated by the LLM"
    )

    # --- FK Relationships ---
    # Correct targets: session_id → chat_sessions, user_id → users.
    # (The previous draft had these swapped; this matches the rest of
    # the entity layer where `messages.session_id` FKs to `chat_sessions.id`
    # and `chat_sessions.user_id` FKs to `users.id`.)
    session_id: Mapped[int | None] = mapped_column(
        ForeignKey("chat_sessions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="FK → chat_sessions.id. Groups traces by conversation.",
    )
    user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="FK → users.id. Tracks per-user query history.",
    )

    # Models used for this specific execution
    llm_model_name: Mapped[str | None] = mapped_column(
        String(100), nullable=True,
        comment="LLM used for generation (e.g., 'meta-llama/Llama-3.1-8B-Instruct')",
    )
    embedding_model_name: Mapped[str | None] = mapped_column(
        String(100), nullable=True,
        comment="Embedding model used for vector search",
    )

    # Performance & Cost Metrics
    input_tokens: Mapped[int | None] = mapped_column(
        Integer, nullable=True, comment="Tokens sent to LLM (prompt context + query)"
    )
    output_tokens: Mapped[int | None] = mapped_column(
        Integer, nullable=True, comment="Tokens generated by LLM"
    )
    retrieval_latency_ms: Mapped[float | None] = mapped_column(
        Float, nullable=True, comment="Time taken for hybrid retrieval in milliseconds"
    )
    rerank_latency_ms: Mapped[float | None] = mapped_column(
        Float, nullable=True, comment="Time taken for the reranker stage in milliseconds"
    )
    llm_latency_ms: Mapped[float | None] = mapped_column(
        Float, nullable=True, comment="Time taken for LLM streaming generation in milliseconds"
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), comment="Timestamp when the log was created"
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(),
        comment="Timestamp when the log was last updated",
    )

    def __repr__(self) -> str:
        preview = (self.original_query[:40] + "...") if len(self.original_query) > 40 else self.original_query
        return f"<RAG_traces(id={self.id}, query='{preview}', technique='{self.transformation_technique}')>"
